///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the webRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c1e34ae3-1882-45c6-b165-aea30d0ab8a6")]
    public partial class webRepository : RepoGenBaseFolder
    {
        static webRepository instance = new webRepository();
        webRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        webRepositoryFolders.ĐăngNhậpSachMềmAppFolder _đăngnhậpsachmềm;

        /// <summary>
        /// Gets the singleton class instance representing the webRepository element repository.
        /// </summary>
        [RepositoryFolder("c1e34ae3-1882-45c6-b165-aea30d0ab8a6")]
        public static webRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public webRepository() 
            : base("webRepository", "/", null, 0, false, "c1e34ae3-1882-45c6-b165-aea30d0ab8a6", ".\\RepositoryImages\\webRepositoryc1e34ae3.rximgres")
        {
            _applicationundertest = new webRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _đăngnhậpsachmềm = new webRepositoryFolders.ĐăngNhậpSachMềmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c1e34ae3-1882-45c6-b165-aea30d0ab8a6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("06831123-e82e-4233-a877-203b8663c949")]
        public virtual webRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềm folder.
        /// </summary>
        [RepositoryFolder("88f86c79-c38c-482b-9b92-79a2069e62c1")]
        public virtual webRepositoryFolders.ĐăngNhậpSachMềmAppFolder ĐăngNhậpSachMềm
        {
            get { return _đăngnhậpsachmềm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class webRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("06831123-e82e-4233-a877-203b8663c949")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            webRepositoryFolders.ContentBoundFolder _contentbound;
            RepoItemInfo _textInfo;
            RepoItemInfo _chatsectionInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "06831123-e82e-4233-a877-203b8663c949", "")
            {
                _contentbound = new webRepositoryFolders.ContentBoundFolder(this);
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'sidebar-wrapper']/?/?/input[@type='text']", 30000, null, "a7a6f488-bb15-422e-8d18-0f85ae49a0dd");
                _chatsectionInfo = new RepoItemInfo(this, "ChatSection", ".//div[#'page-content-wrapper']/div[3]/div/div", 30000, null, "55b63792-6d4e-4519-82fa-7be6dbab5716");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("06831123-e82e-4233-a877-203b8663c949")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("06831123-e82e-4233-a877-203b8663c949")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("a7a6f488-bb15-422e-8d18-0f85ae49a0dd")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("a7a6f488-bb15-422e-8d18-0f85ae49a0dd")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The ChatSection item.
            /// </summary>
            [RepositoryItem("55b63792-6d4e-4519-82fa-7be6dbab5716")]
            public virtual Ranorex.DivTag ChatSection
            {
                get
                {
                    return _chatsectionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ChatSection item info.
            /// </summary>
            [RepositoryItemInfo("55b63792-6d4e-4519-82fa-7be6dbab5716")]
            public virtual RepoItemInfo ChatSectionInfo
            {
                get
                {
                    return _chatsectionInfo;
                }
            }

            /// <summary>
            /// The ContentBound folder.
            /// </summary>
            [RepositoryFolder("a27a85ef-e879-48b2-a8a1-8d910ea67660")]
            public virtual webRepositoryFolders.ContentBoundFolder ContentBound
            {
                get { return _contentbound; }
            }
        }

        /// <summary>
        /// The ContentBoundFolder folder.
        /// </summary>
        [RepositoryFolder("a27a85ef-e879-48b2-a8a1-8d910ea67660")]
        public partial class ContentBoundFolder : RepoGenBaseFolder
        {
            RepoItemInfo _kiểmthửInfo;
            RepoItemInfo _đăngnhậpInfo;
            RepoItemInfo _divtagnhắntintraođổiInfo;
            RepoItemInfo _lớphọccủatoiInfo;
            RepoItemInfo _gửitinnhắnInfo;
            RepoItemInfo _buttontaggửiInfo;
            RepoItemInfo _spantagabcInfo;

            /// <summary>
            /// Creates a new ContentBound  folder.
            /// </summary>
            public ContentBoundFolder(RepoGenBaseFolder parentFolder) :
                    base("ContentBound", "body/tag[@tagname='app-root']/div[2]", parentFolder, 30000, null, false, "a27a85ef-e879-48b2-a8a1-8d910ea67660", "")
            {
                _kiểmthửInfo = new RepoItemInfo(this, "KiểmThử", ".//tag[@tagname='app-list-class']/ul[1]/li[1]/div/div[1]/a[@innertext='Kiểm Thử']", 30000, null, "b2dd8976-36e1-42e7-80e1-a2d3e7a63815");
                _đăngnhậpInfo = new RepoItemInfo(this, "ĐăngNhập", "div//div[@innertext~'^\\ \\ Để\\ sử\\ dụng\\ bạn\\ cần\\ \\ ho']/a[@innertext='Đăng nhập']", 30000, null, "cd0b19f4-f5f1-4ca7-8886-9345ba5f2497");
                _divtagnhắntintraođổiInfo = new RepoItemInfo(this, "DivTagNhắnTinTraoĐổi", "div//tag[@tagname='app-action']/div/div[1]/div[@innertext=' Nhắn tin, trao đổi    ']", 30000, null, "e5a95408-3b85-4b0a-957b-a918ce453544");
                _lớphọccủatoiInfo = new RepoItemInfo(this, "LớpHọcCủaToi", "div/div//ul/li[1]//a[@innertext='Lớp học của tôi']", 30000, null, "f9eb39be-47fc-4e8f-8c30-bd6b645a28a8");
                _gửitinnhắnInfo = new RepoItemInfo(this, "GửiTinNhắn", ".//textarea[@placeholder='Gửi tin nhắn']", 30000, null, "478d2330-f8c5-45ea-9dc3-75064451d315");
                _buttontaggửiInfo = new RepoItemInfo(this, "ButtonTagGửi", ".//button[@innertext=' Gửi              ']", 30000, null, "b39ee3ba-b751-4382-8103-797af299eeb0");
                _spantagabcInfo = new RepoItemInfo(this, "SpanTagAbc", "div[3]//blockquote/span[@innertext='abc']", 30000, null, "871d55e6-6baf-4adb-87d8-434135352894");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a27a85ef-e879-48b2-a8a1-8d910ea67660")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a27a85ef-e879-48b2-a8a1-8d910ea67660")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The KiểmThử item.
            /// </summary>
            [RepositoryItem("b2dd8976-36e1-42e7-80e1-a2d3e7a63815")]
            public virtual Ranorex.ATag KiểmThử
            {
                get
                {
                    return _kiểmthửInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The KiểmThử item info.
            /// </summary>
            [RepositoryItemInfo("b2dd8976-36e1-42e7-80e1-a2d3e7a63815")]
            public virtual RepoItemInfo KiểmThửInfo
            {
                get
                {
                    return _kiểmthửInfo;
                }
            }

            /// <summary>
            /// The ĐăngNhập item.
            /// </summary>
            [RepositoryItem("cd0b19f4-f5f1-4ca7-8886-9345ba5f2497")]
            public virtual Ranorex.ATag ĐăngNhập
            {
                get
                {
                    return _đăngnhậpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("cd0b19f4-f5f1-4ca7-8886-9345ba5f2497")]
            public virtual RepoItemInfo ĐăngNhậpInfo
            {
                get
                {
                    return _đăngnhậpInfo;
                }
            }

            /// <summary>
            /// The DivTagNhắnTinTraoĐổi item.
            /// </summary>
            [RepositoryItem("e5a95408-3b85-4b0a-957b-a918ce453544")]
            public virtual Ranorex.DivTag DivTagNhắnTinTraoĐổi
            {
                get
                {
                    return _divtagnhắntintraođổiInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagNhắnTinTraoĐổi item info.
            /// </summary>
            [RepositoryItemInfo("e5a95408-3b85-4b0a-957b-a918ce453544")]
            public virtual RepoItemInfo DivTagNhắnTinTraoĐổiInfo
            {
                get
                {
                    return _divtagnhắntintraođổiInfo;
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item.
            /// </summary>
            [RepositoryItem("f9eb39be-47fc-4e8f-8c30-bd6b645a28a8")]
            public virtual Ranorex.ATag LớpHọcCủaToi
            {
                get
                {
                    return _lớphọccủatoiInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item info.
            /// </summary>
            [RepositoryItemInfo("f9eb39be-47fc-4e8f-8c30-bd6b645a28a8")]
            public virtual RepoItemInfo LớpHọcCủaToiInfo
            {
                get
                {
                    return _lớphọccủatoiInfo;
                }
            }

            /// <summary>
            /// The GửiTinNhắn item.
            /// </summary>
            [RepositoryItem("478d2330-f8c5-45ea-9dc3-75064451d315")]
            public virtual Ranorex.TextAreaTag GửiTinNhắn
            {
                get
                {
                    return _gửitinnhắnInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The GửiTinNhắn item info.
            /// </summary>
            [RepositoryItemInfo("478d2330-f8c5-45ea-9dc3-75064451d315")]
            public virtual RepoItemInfo GửiTinNhắnInfo
            {
                get
                {
                    return _gửitinnhắnInfo;
                }
            }

            /// <summary>
            /// The ButtonTagGửi item.
            /// </summary>
            [RepositoryItem("b39ee3ba-b751-4382-8103-797af299eeb0")]
            public virtual Ranorex.ButtonTag ButtonTagGửi
            {
                get
                {
                    return _buttontaggửiInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagGửi item info.
            /// </summary>
            [RepositoryItemInfo("b39ee3ba-b751-4382-8103-797af299eeb0")]
            public virtual RepoItemInfo ButtonTagGửiInfo
            {
                get
                {
                    return _buttontaggửiInfo;
                }
            }

            /// <summary>
            /// The SpanTagAbc item.
            /// </summary>
            [RepositoryItem("871d55e6-6baf-4adb-87d8-434135352894")]
            public virtual Ranorex.SpanTag SpanTagAbc
            {
                get
                {
                    return _spantagabcInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagAbc item info.
            /// </summary>
            [RepositoryItemInfo("871d55e6-6baf-4adb-87d8-434135352894")]
            public virtual RepoItemInfo SpanTagAbcInfo
            {
                get
                {
                    return _spantagabcInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("88f86c79-c38c-482b-9b92-79a2069e62c1")]
        public partial class ĐăngNhậpSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _commitInfo;

            /// <summary>
            /// Creates a new ĐăngNhậpSachMềm  folder.
            /// </summary>
            public ĐăngNhậpSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngNhậpSachMềm", "/dom[@domain='accounts.sachmem.vn']", parentFolder, 30000, null, false, "88f86c79-c38c-482b-9b92-79a2069e62c1", "")
            {
                _commitInfo = new RepoItemInfo(this, "Commit", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "edaf3171-91fa-4540-aa95-38322a103476");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("88f86c79-c38c-482b-9b92-79a2069e62c1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("88f86c79-c38c-482b-9b92-79a2069e62c1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("edaf3171-91fa-4540-aa95-38322a103476")]
            public virtual Ranorex.InputTag Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("edaf3171-91fa-4540-aa95-38322a103476")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
