///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace web.recodermodul
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording10 recording.
    /// </summary>
    [TestModule("62a70ae1-4454-4059-96a1-f5ae1a473cdd", ModuleType.Recording, 1)]
    public partial class Recording10 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::web.webRepository repository.
        /// </summary>
        public static global::web.webRepository repo = global::web.webRepository.Instance;

        static Recording10 instance = new Recording10();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording10()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording10 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'ApplicationUnderTest.ContentBound.GửiTinNhắn'.", repo.ApplicationUnderTest.ContentBound.GửiTinNhắnInfo, new RecordItemIndex(0));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.ContentBound.GửiTinNhắn);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ANH' with focus on 'ApplicationUnderTest.ContentBound.GửiTinNhắn'.", repo.ApplicationUnderTest.ContentBound.GửiTinNhắnInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ContentBound.GửiTinNhắn.PressKeys("ANH");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='ANH') on item 'ApplicationUnderTest.ContentBound.GửiTinNhắn'.", repo.ApplicationUnderTest.ContentBound.GửiTinNhắnInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.ContentBound.GửiTinNhắnInfo, "Value", "ANH");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'ApplicationUnderTest.ContentBound.GửiTinNhắn'.", repo.ApplicationUnderTest.ContentBound.GửiTinNhắnInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.ContentBound.GửiTinNhắn);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'anh' with focus on 'ApplicationUnderTest.ContentBound.GửiTinNhắn'.", repo.ApplicationUnderTest.ContentBound.GửiTinNhắnInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.ContentBound.GửiTinNhắn.PressKeys("anh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='anh') on item 'ApplicationUnderTest.ContentBound.GửiTinNhắn'.", repo.ApplicationUnderTest.ContentBound.GửiTinNhắnInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.ContentBound.GửiTinNhắnInfo, "Value", "anh");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
